services:
  httpd:
    image: wsams/httpd:php
    ports:
      - "443:443"
      - "80:80"
    environment:
      - HTTPD_SERVER_NAME=localhost
      - HTTPD_SERVER_ADMIN=webmaster@example.com
      - SSL_CERTIFICATE_FILE=/apache-cert.pem
      - SSL_CERTIFICATE_KEY_FILE=/apache-key.pem
    volumes:
      - ./examples:/var/www/html
    restart: always
