version: '3'
services:
  proxy:
    image: wsams/httpd
    ports:
      - 443:443
    environment:
      - HTTP_SERVER_NAME=localhost
      - HTTP_SERVER_ADMIN=webmaster@example.com
      - SSL_CERTIFICATE_FILE=/apache-cert.pem
      - SSL_CERTIFICATE_KEY_FILE=/apache-key.pem
    volumes:
      - ./html:/var/www/html
    restart: always
