version: '3'
services:
  proxy:
    image: wsams/httpd
    ports:
      - 443:443
    environment:
      - HTTP_SERVER_NAME=example.com
      - HTTP_SERVER_ADMIN=webmaster@example.com
      - SSL_CERTIFICATE_FILE=/etc/letsencrypt/live/example.com/fullchain.pem
      - SSL_CERTIFICATE_KEY_FILE=/etc/letsencrypt/live/example.com/privkey.pem
    volumes:
      - ./html:/var/www/html
      - /etc/letsencrypt/live/example.com:/etc/letsencrypt/live/example.com
    restart: always
